INSERT INTO PLANO_DE_ASSINATURA (NOME, VALOR_MENSAL) VALUES ('Gratuito', 0);
INSERT INTO PLANO_DE_ASSINATURA (NOME, VALOR_MENSAL) VALUES ('Pro', 5000);
INSERT INTO PLANO_DE_ASSINATURA (NOME, VALOR_MENSAL) VALUES ('Pro Max', 8000);
INSERT INTO PLANO_DE_ASSINATURA (NOME, VALOR_MENSAL, REMOVIDO_EM) VALUES ('Super Pro', 10000, CURRENT_TIMESTAMP);
