CREATE TABLE IF NOT EXISTS PLANO_DE_ASSINATURA (
    ID INTEGER PRIMARY KEY,
    NOME TEXT UNIQUE NOT NULL,
    VALOR_MENSAL INTEGER NOT NULL,
    CRIADO_EM TEXT DEFAULT CURRENT_TIMESTAMP NOT NULL,
    ATUALIZADO_EM TEXT DEFAULT CURRENT_TIMESTAMP NOT NULL,
    REMOVIDO_EM TEXT
);

CREATE TABLE IF NOT EXISTS USUARIO (
    ID INTEGER PRIMARY KEY,
    CPF TEXT UNIQUE NOT NULL,
    NOME TEXT NOT NULL,
    NOME_DE_USUARIO TEXT UNIQUE NOT NULL,
    EMAIL TEXT UNIQUE NOT NULL,
    SENHA TEXT NOT NULL,
    DATA_DE_NASCIMENTO TEXT NOT NULL,
    PLANO_DE_ASSINATURA INTEGER NOT NULL,
    CRIADO_EM TEXT DEFAULT CURRENT_TIMESTAMP NOT NULL,
    ATUALIZADO_EM TEXT DEFAULT CURRENT_TIMESTAMP NOT NULL,
    REMOVIDO_EM TEXT,
    FOREIGN KEY(PLANO_DE_ASSINATURA) REFERENCES PLANO_DE_ASSINATURA(ID)
);

CREATE TABLE IF NOT EXISTS LINK (
    ID INTEGER PRIMARY KEY,
    NOME TEXT NOT NULL,
    CODIGO_HASH TEXT UNIQUE NOT NULL,
    LINK_WHATSAPP TEXT,
    LINK_TELEGRAM TEXT,
    ORDEM_DE_REDIRECIONAMENTO TEXT NOT NULL,
    USUARIO INTEGER NOT NULL,
    CRIADO_EM TEXT DEFAULT CURRENT_TIMESTAMP NOT NULL,
    ATUALIZADO_EM TEXT DEFAULT CURRENT_TIMESTAMP NOT NULL,
    REMOVIDO_EM TEXT,
    FOREIGN KEY(USUARIO) REFERENCES USUARIO(ID)
);

CREATE TABLE IF NOT EXISTS HISTORICO (
    ID INTEGER PRIMARY KEY,
    USUARIO INTEGER,
    VALOR_ORIGINAL TEXT,
    VALOR_NOVO TEXT,
    TABELA_MODIFICADA TEXT NOT NULL,
    CRIADO_EM TEXT NOT NULL,
    FOREIGN KEY(USUARIO) REFERENCES USUARIO(ID)
);
