INSERT INTO PLANO_DE_ASSINATURA (NOME, VALOR_MENSAL, LIMITE, PERIODO_LIMITE) VALUES ('Gratuito', 0, 50, 'h');
INSERT INTO PLANO_DE_ASSINATURA (NOME, VALOR_MENSAL, LIMITE, PERIODO_LIMITE) VALUES ('Pro', 5000, 500, 'm');
INSERT INTO PLANO_DE_ASSINATURA (NOME, VALOR_MENSAL, LIMITE, PERIODO_LIMITE) VALUES ('Pro Max', 8000, 10000, 'd');
INSERT INTO PLANO_DE_ASSINATURA (NOME, VALOR_MENSAL, LIMITE, PERIODO_LIMITE, REMOVIDO_EM) VALUES ('Super Pro', 10000, 10000, 'M', CURRENT_TIMESTAMP);
