// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.543
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func LinkCreateForm() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<form id=\"create-link\" class=\"bg-rprimary flex flex-col gap-3 p-3 rounded-lg text-rlightest w-1/3\"><h3 class=\"font-extrabold text-2xl\">Criar um novo Link</h3><input id=\"link_create_nome\" name=\"link_create_nome\" class=\"bg-transparent border-b border-rlighter placeholder:text-rlighter px-1 text-lg\" type=\"text\" placeholder=\"Nome\"> <input id=\"link_create_link_whatsapp\" name=\"link_create_link_whatsapp\" class=\"bg-transparent border-b border-rlighter placeholder:text-rlighter px-1 text-lg\" type=\"text\" placeholder=\"Número do Whatsapp\"> <input id=\"link_create_link_telegram\" name=\"link_create_link_telegram\" class=\"bg-transparent border-b border-rlighter placeholder:text-rlighter px-1 text-lg\" type=\"text\" placeholder=\"Link do Telegram\"> <input id=\"link_create_ordem_de_redirecionamento\" name=\"link_create_ordem_de_redirecionamento\" class=\"bg-transparent border-b border-rlighter placeholder:text-rlighter px-1 text-lg\" type=\"text\" placeholder=\"Ordem de Redirecionamento\"><div class=\"flex items-center justify-between px-20\"><button class=\"text-xl\" type=\"button\" hx-get=\"/web/link_create_button\" hx-trigger=\"click\" hx-target=\"#create-link\" hx-swap=\"outerHTML\">Cancelar</button> <button class=\"text-xl\" type=\"submit\" hx-post=\"/web/link_create\" hx-trigger=\"click\" hx-target=\"#create-link\" hx-swap=\"outerHTML\">Enviar</button></div></form>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
