// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Equipe da DevOps (Pablo Eduardo, Guilherme Bernardo e Eduardo Henrique)",
            "email": "comercialdevops@gmail.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/links/historico": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Histórico"
                ],
                "summary": "Retorna o histórico de ações relativas a links no sistema",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/HistoricoLink"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    }
                }
            }
        },
        "/planos_de_assinatura": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Planos de Assinatura"
                ],
                "summary": "Retorna os planos de assinatura",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/PlanoDeAssinatura"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Planos de Assinatura"
                ],
                "summary": "Cria um plano de assinatura",
                "parameters": [
                    {
                        "description": "Nome",
                        "name": "nome",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "Valor Mensal",
                        "name": "valor_mensal",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "integer"
                        }
                    },
                    {
                        "description": "Limite de Links Mensal",
                        "name": "limite_links_mensal",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "integer"
                        }
                    },
                    {
                        "description": "Ordenação Aleatória de Links",
                        "name": "ordenacao_aleatoria_links",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "boolean"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    }
                }
            }
        },
        "/planos_de_assinatura/:nome": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Planos de Assinatura"
                ],
                "summary": "Retorna o plano de assinatura com o nome fornecido",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Nome",
                        "name": "nome",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/PlanoDeAssinatura"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    }
                }
            },
            "delete": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Planos de Assinatura"
                ],
                "summary": "Remove um plano de assinatura",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Nome",
                        "name": "nome",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    }
                }
            },
            "patch": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Planos de Assinatura"
                ],
                "summary": "Atualiza um plano de assinatura",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Nome",
                        "name": "nome",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Nome",
                        "name": "nome",
                        "in": "body",
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "Valor Mensal",
                        "name": "valor_mensal",
                        "in": "body",
                        "schema": {
                            "type": "integer"
                        }
                    },
                    {
                        "description": "Limite de Links Mensal",
                        "name": "limite_links_mensal",
                        "in": "body",
                        "schema": {
                            "type": "integer"
                        }
                    },
                    {
                        "description": "Ordenação Aleatória de Links",
                        "name": "ordenacao_aleatoria_links",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "boolean"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    }
                }
            }
        },
        "/planos_de_assinatura/historico": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Histórico"
                ],
                "summary": "Retorna o histórico de ações relativas a planos de assinatura no sistema",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/HistoricoPlanoDeAssinatura"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    }
                }
            }
        },
        "/redirecionadores": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Redirecionadores"
                ],
                "summary": "Cria um redirecionador",
                "parameters": [
                    {
                        "description": "Nome",
                        "name": "nome",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "Ordem de Redirecionamento",
                        "name": "ordem_de_redirecionamento",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "Nome de Usuário",
                        "name": "nome_de_usuario",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    }
                }
            }
        },
        "/redirecionadores/:codigo_hash": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Redirecionadors"
                ],
                "summary": "Retorna o redirecionador com o código hash fornecido",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Código Hash",
                        "name": "codigo_hash",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Redirecionador"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    }
                }
            },
            "delete": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Redirecionadors"
                ],
                "summary": "Remove um redirecionador",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Código Hash",
                        "name": "codigo_hash",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    }
                }
            },
            "patch": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Redirecionadores"
                ],
                "summary": "Atualiza um redirecionador",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Código Hash",
                        "name": "codigo_hash",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Nome",
                        "name": "nome",
                        "in": "body",
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "Ordem de Redirecionamento",
                        "name": "ordem_de_redirecionamento",
                        "in": "body",
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    }
                }
            }
        },
        "/redirecionadores/:codigo_hash/link/:id": {
            "delete": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Links"
                ],
                "summary": "Remove um link específico de um redirecionador específico",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Código Hash",
                        "name": "codigo_hash",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    }
                }
            },
            "patch": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Links"
                ],
                "summary": "Atualiza um link específico de um redirecionador específico",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Código Hash",
                        "name": "codigo_hash",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Nome",
                        "name": "nome",
                        "in": "body",
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "Link",
                        "name": "link",
                        "in": "body",
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "Plataforma",
                        "name": "plataforma",
                        "in": "body",
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    }
                }
            }
        },
        "/redirecionadores/:codigo_hash/links": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Links"
                ],
                "summary": "Retorna os links do redirecionador com o código hash fornecido",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Código Hash",
                        "name": "codigo_hash",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/Link"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Links"
                ],
                "summary": "Cria links no redirecionador com o código hash fornecido",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Código Hash",
                        "name": "codigo_hash",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Links",
                        "name": "links",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.LinkToBatchInsert"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    }
                }
            }
        },
        "/redirecionadores/:codigo_hash/links/:id": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Links"
                ],
                "summary": "Retorna o link com o id fornecido do redirecionador com o código hash fornecido",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Código Hash",
                        "name": "codigo_hash",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Link"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    }
                }
            }
        },
        "/redirecionadores/:nome_de_usuario": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Redirecionadores"
                ],
                "summary": "Retorna os redirecionadores",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Nome de Usuário",
                        "name": "nome_de_usuario",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/Redirecionador"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    }
                }
            }
        },
        "/redirecionadores/historico": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Histórico"
                ],
                "summary": "Retorna o histórico de ações relativas a redirecionadores no sistema",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/HistoricoRedirecionador"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    }
                }
            }
        },
        "/redirecionadores/rehash/:codigo_hash": {
            "patch": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Redirecionadores"
                ],
                "summary": "Recria o hash de um redirecionador",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Código Hash",
                        "name": "codigo_hash",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    }
                }
            }
        },
        "/usuarios": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Usuários"
                ],
                "summary": "Retorna todos os usuários",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/Usuario"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    }
                }
            }
        },
        "/usuarios/:nome_de_usuario": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Usuários"
                ],
                "summary": "Retorna o usuário com o nome de usuário fornecido",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Nome de Usuário",
                        "name": "nome_de_usuario",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Usuario"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    }
                }
            },
            "delete": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Usuários"
                ],
                "summary": "Remove um usuário",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Nome de Usuário",
                        "name": "nome_de_usuario",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    }
                }
            },
            "patch": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Usuários"
                ],
                "summary": "Atualiza um usuário",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Nome de Usuário",
                        "name": "nome_de_usuario",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "CPF",
                        "name": "cpf",
                        "in": "body",
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "Nome",
                        "name": "nome",
                        "in": "body",
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "Nome de Usuário",
                        "name": "nome_de_usuario",
                        "in": "body",
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "Email",
                        "name": "email",
                        "in": "body",
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "Senha",
                        "name": "senha",
                        "in": "body",
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "Data de Nascimento",
                        "name": "data_de_nascimento",
                        "in": "body",
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "Plano de Assinatura",
                        "name": "plano_de_assinatura",
                        "in": "body",
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    }
                }
            }
        },
        "/usuarios/:nome_de_usuario/troca_de_senha": {
            "patch": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Usuários"
                ],
                "summary": "Exige a troca de senha de um usuário",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Nome de Usuário",
                        "name": "nome_de_usuario",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    }
                }
            }
        },
        "/usuarios/criar_permanente/:valor": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Usuários"
                ],
                "summary": "Cria um usuário permanente a partir de um temporário",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Valor",
                        "name": "valor",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Senha Nova",
                        "name": "senha_nova",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "Data de Nascimento",
                        "name": "data_de_nascimento",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    }
                }
            }
        },
        "/usuarios/historico": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Histórico"
                ],
                "summary": "Retorna o histórico de ações relativas a usuários no sistema",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/HistoricoUsuario"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    }
                }
            }
        },
        "/usuarios/login": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Usuários"
                ],
                "summary": "Autentica o usuário",
                "parameters": [
                    {
                        "description": "Email",
                        "name": "email",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "Senha",
                        "name": "senha",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    }
                }
            }
        },
        "/usuarios/troca_de_senha/:valor": {
            "patch": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Usuários"
                ],
                "summary": "Troca a senha de um usuário",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Valor",
                        "name": "valor",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Senha Nova",
                        "name": "senha_nova",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    }
                }
            }
        },
        "/usuarios_temporarios": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "UsuáriosTemporários"
                ],
                "summary": "Cria um usuário temporário",
                "parameters": [
                    {
                        "description": "Request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/ParametrosKirvano"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    }
                }
            }
        },
        "/usuarios_temporarios/historico": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Histórico"
                ],
                "summary": "Retorna o histórico de ações relativas a usuários temporários no sistema",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/HistoricoUsuarioTemporario"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "HistoricoLink": {
            "type": "object",
            "properties": {
                "atualizado_em": {
                    "$ref": "#/definitions/sql.NullString"
                },
                "bitmask": {
                    "type": "integer"
                },
                "criado_em": {
                    "$ref": "#/definitions/sql.NullString"
                },
                "criado_em_": {
                    "type": "string"
                },
                "id": {
                    "$ref": "#/definitions/sql.NullInt64"
                },
                "link": {
                    "$ref": "#/definitions/sql.NullString"
                },
                "plataforma": {
                    "$ref": "#/definitions/sql.NullString"
                },
                "redirecionador": {
                    "$ref": "#/definitions/sql.NullInt64"
                },
                "removido_em": {
                    "type": "string"
                },
                "rowid": {
                    "type": "integer"
                },
                "versao": {
                    "type": "integer"
                }
            }
        },
        "HistoricoPlanoDeAssinatura": {
            "type": "object",
            "properties": {
                "atualizado_em": {
                    "$ref": "#/definitions/sql.NullString"
                },
                "bitmask": {
                    "type": "integer"
                },
                "criado_em": {
                    "$ref": "#/definitions/sql.NullString"
                },
                "criado_em_": {
                    "type": "string"
                },
                "id": {
                    "$ref": "#/definitions/sql.NullInt64"
                },
                "limite_links_mensal": {
                    "$ref": "#/definitions/sql.NullInt64"
                },
                "nome": {
                    "$ref": "#/definitions/sql.NullString"
                },
                "ordenacao_aleatoria_links": {
                    "$ref": "#/definitions/sql.NullBool"
                },
                "removido_em": {
                    "type": "integer"
                },
                "rowid": {
                    "type": "integer"
                },
                "valor_mensal": {
                    "$ref": "#/definitions/sql.NullInt64"
                },
                "versao": {
                    "type": "integer"
                }
            }
        },
        "HistoricoRedirecionador": {
            "type": "object",
            "properties": {
                "atualizado_em": {
                    "$ref": "#/definitions/sql.NullString"
                },
                "bitmask": {
                    "type": "integer"
                },
                "codigo_hash": {
                    "$ref": "#/definitions/sql.NullString"
                },
                "criado_em": {
                    "$ref": "#/definitions/sql.NullString"
                },
                "criado_em_": {
                    "type": "string"
                },
                "id": {
                    "$ref": "#/definitions/sql.NullInt64"
                },
                "nome": {
                    "$ref": "#/definitions/sql.NullString"
                },
                "ordem_de_redirecionamento": {
                    "$ref": "#/definitions/sql.NullString"
                },
                "removido_em": {
                    "type": "string"
                },
                "rowid": {
                    "type": "integer"
                },
                "usuario": {
                    "$ref": "#/definitions/sql.NullInt64"
                },
                "versao": {
                    "type": "integer"
                }
            }
        },
        "HistoricoUsuario": {
            "type": "object",
            "properties": {
                "atualizado_em": {
                    "$ref": "#/definitions/sql.NullString"
                },
                "bitmask": {
                    "type": "integer"
                },
                "cpf": {
                    "$ref": "#/definitions/sql.NullString"
                },
                "criado_em": {
                    "$ref": "#/definitions/sql.NullString"
                },
                "criado_em_": {
                    "type": "string"
                },
                "data_de_nascimento": {
                    "$ref": "#/definitions/sql.NullString"
                },
                "email": {
                    "$ref": "#/definitions/sql.NullString"
                },
                "id": {
                    "$ref": "#/definitions/sql.NullInt64"
                },
                "nome": {
                    "$ref": "#/definitions/sql.NullString"
                },
                "nome_de_usuario": {
                    "$ref": "#/definitions/sql.NullString"
                },
                "plano_de_assinatura": {
                    "$ref": "#/definitions/sql.NullInt64"
                },
                "removido_em": {
                    "type": "string"
                },
                "rowid": {
                    "type": "integer"
                },
                "senha": {
                    "$ref": "#/definitions/sql.NullString"
                },
                "versao": {
                    "type": "integer"
                }
            }
        },
        "HistoricoUsuarioTemporario": {
            "type": "object",
            "properties": {
                "bitmask": {
                    "type": "integer"
                },
                "cpf": {
                    "$ref": "#/definitions/sql.NullString"
                },
                "criado_em": {
                    "$ref": "#/definitions/sql.NullString"
                },
                "criado_em_": {
                    "type": "string"
                },
                "email": {
                    "$ref": "#/definitions/sql.NullString"
                },
                "id": {
                    "$ref": "#/definitions/sql.NullInt64"
                },
                "nome": {
                    "$ref": "#/definitions/sql.NullString"
                },
                "nome_de_usuario": {
                    "$ref": "#/definitions/sql.NullString"
                },
                "plano_de_assinatura": {
                    "$ref": "#/definitions/sql.NullInt64"
                },
                "removido_em": {
                    "type": "string"
                },
                "rowid": {
                    "type": "integer"
                },
                "versao": {
                    "type": "integer"
                }
            }
        },
        "Link": {
            "type": "object",
            "properties": {
                "atualizado_em": {
                    "type": "string"
                },
                "criado_em": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "link": {
                    "type": "string"
                },
                "nome": {
                    "type": "string"
                },
                "plataforma": {
                    "type": "string"
                },
                "redirecionador": {
                    "type": "string"
                },
                "removido_em": {
                    "type": "string"
                }
            }
        },
        "ParametrosKirvano": {
            "type": "object",
            "properties": {
                "customer": {
                    "$ref": "#/definitions/server.customerData"
                },
                "event": {
                    "type": "string"
                },
                "products": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/server.productData"
                    }
                }
            }
        },
        "PlanoDeAssinatura": {
            "type": "object",
            "properties": {
                "atualizado_em": {
                    "type": "string"
                },
                "criado_em": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "limite_links_mensal": {
                    "type": "integer"
                },
                "nome": {
                    "type": "string"
                },
                "ordenacao_aleatoria_links": {
                    "type": "boolean"
                },
                "removido_em": {
                    "type": "integer"
                },
                "valor_mensal": {
                    "type": "integer"
                }
            }
        },
        "Redirecionador": {
            "type": "object",
            "properties": {
                "atualizado_em": {
                    "type": "string"
                },
                "codigo_hash": {
                    "type": "string"
                },
                "criado_em": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "nome": {
                    "type": "string"
                },
                "ordem_de_redirecionamento": {
                    "type": "string"
                },
                "removido_em": {
                    "type": "string"
                },
                "usuario": {
                    "type": "string"
                }
            }
        },
        "Usuario": {
            "type": "object",
            "properties": {
                "atualizado_em": {
                    "type": "string"
                },
                "cpf": {
                    "type": "string"
                },
                "criado_em": {
                    "type": "string"
                },
                "data_de_nascimento": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "nome": {
                    "type": "string"
                },
                "nome_de_usuario": {
                    "type": "string"
                },
                "plano_de_assinatura": {
                    "type": "integer"
                },
                "removido_em": {
                    "type": "string"
                },
                "senha": {
                    "type": "string"
                }
            }
        },
        "echo.HTTPError": {
            "type": "object",
            "properties": {
                "message": {}
            }
        },
        "models.LinkToBatchInsert": {
            "type": "object",
            "properties": {
                "link": {
                    "type": "string"
                },
                "nome": {
                    "type": "string"
                },
                "plataforma": {
                    "type": "string"
                }
            }
        },
        "server.customerData": {
            "type": "object",
            "properties": {
                "document": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "server.productData": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                }
            }
        },
        "sql.NullBool": {
            "type": "object",
            "properties": {
                "bool": {
                    "type": "boolean"
                },
                "valid": {
                    "description": "Valid is true if Bool is not NULL",
                    "type": "boolean"
                }
            }
        },
        "sql.NullInt64": {
            "type": "object",
            "properties": {
                "int64": {
                    "type": "integer"
                },
                "valid": {
                    "description": "Valid is true if Int64 is not NULL",
                    "type": "boolean"
                }
            }
        },
        "sql.NullString": {
            "type": "object",
            "properties": {
                "string": {
                    "type": "string"
                },
                "valid": {
                    "description": "Valid is true if String is not NULL",
                    "type": "boolean"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "API do Redirectify",
	Description:      "API para interagir com o Redirectify",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
