definitions:
  Erro:
    properties:
      message: {}
    type: object
  Historico:
    properties:
      criado_em:
        type: string
      id:
        type: integer
      tabela_modificada:
        type: string
      usuario:
        type: integer
      valor_novo:
        type: string
      valor_original:
        type: string
    type: object
  Link:
    properties:
      atualizado_em:
        type: string
      codigo_hash:
        type: string
      criado_em:
        type: string
      id:
        type: integer
      link_telegram:
        type: string
      link_whatsapp:
        type: string
      nome:
        type: string
      ordem_de_redirecionamento:
        type: string
      removido_em:
        type: string
      usuario:
        type: integer
    type: object
  PlanoDeAssinatura:
    properties:
      atualizado_em:
        type: string
      criado_em:
        type: string
      id:
        type: integer
      nome:
        type: string
      removido_em:
        type: integer
      valor_mensal:
        type: integer
    type: object
  Usuario:
    properties:
      atualizado_em:
        type: string
      cpf:
        type: string
      criado_em:
        type: string
      data_de_nascimento:
        type: string
      email:
        type: string
      id:
        type: integer
      nome:
        type: string
      nome_de_usuario:
        type: string
      plano_de_assinatura:
        type: integer
      removido_em:
        type: string
      senha:
        type: string
    type: object
info:
  contact:
    email: test@test.com
    name: Equipe da DevOps (Pablo, Guilherme e Eduardo)
  description: API para interagir com o Redirect Max
  title: API do Redirect Max
  version: 0.0.0-alpha
paths:
  /api/historico:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/Historico'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/Erro'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/Erro'
      summary: Retorna o histórico de ações no sistema
      tags:
      - Histórico
  /api/link:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/Link'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/Erro'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/Erro'
      summary: Retorna os links
      tags:
      - Link
    post:
      consumes:
      - application/json
      parameters:
      - description: Nome
        in: body
        name: nome
        required: true
        schema:
          type: string
      - description: Link Whatsapp
        in: body
        name: link_whatsapp
        schema:
          type: string
      - description: Link Telegram
        in: body
        name: link_telegram
        schema:
          type: string
      - description: Ordem de Redirecionamento
        in: body
        name: ordem_de_redirecionamento
        required: true
        schema:
          type: string
      - description: Usuário
        in: body
        name: usuario
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/Erro'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/Erro'
      summary: Cria um link
      tags:
      - Link
  /api/link/:codigo_hash:
    delete:
      consumes:
      - application/json
      parameters:
      - description: Código Hash
        in: path
        name: codigo_hash
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/Erro'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/Erro'
      summary: Remove um link
      tags:
      - Link
    get:
      consumes:
      - application/json
      parameters:
      - description: Nome de Usuário
        in: path
        name: codigo_hash
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Link'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/Erro'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/Erro'
      summary: Retorna o link com o código hash fornecido
      tags:
      - Link
    patch:
      consumes:
      - application/json
      parameters:
      - description: Código Hash
        in: path
        name: codigo_hash
        required: true
        type: string
      - description: Nome
        in: body
        name: nome
        schema:
          type: string
      - description: Link Whatsapp
        in: body
        name: link_whatsapp
        schema:
          type: string
      - description: Link Telegram
        in: body
        name: link_telegram
        schema:
          type: string
      - description: Ordem de Redirecionamento
        in: body
        name: ordem_de_redirecionamento
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/Erro'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/Erro'
      summary: Atualiza um link
      tags:
      - Link
  /api/plano_de_assinatura:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/PlanoDeAssinatura'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/Erro'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/Erro'
      summary: Retorna os planos de assinatura
      tags:
      - Plano de Assinatura
    post:
      consumes:
      - application/json
      parameters:
      - description: Nome
        in: body
        name: nome
        required: true
        schema:
          type: string
      - description: Valor Mensal
        in: body
        name: valor_mensal
        required: true
        schema:
          type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/Erro'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/Erro'
      summary: Cria um plano de assinatura
      tags:
      - Plano de Assinatura
  /api/plano_de_assinatura/:nome:
    delete:
      consumes:
      - application/json
      parameters:
      - description: Nome
        in: path
        name: nome
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/Erro'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/Erro'
      summary: Remove um plano de assinatura
      tags:
      - Plano de Assinatura
    get:
      consumes:
      - application/json
      parameters:
      - description: Nome
        in: path
        name: nome
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/PlanoDeAssinatura'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/Erro'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/Erro'
      summary: Retorna o plano de assinatura com o nome fornecido
      tags:
      - Plano de Assinatura
    patch:
      consumes:
      - application/json
      parameters:
      - description: Nome
        in: path
        name: nome
        required: true
        type: string
      - description: Nome
        in: body
        name: nome
        schema:
          type: string
      - description: Valor Mensal
        in: body
        name: valor_mensal
        schema:
          type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/Erro'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/Erro'
      summary: Atualiza um plano de assinatura
      tags:
      - Plano de Assinatura
  /api/usuario:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/Usuario'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/Erro'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/Erro'
      summary: Retorna todos os usuários
      tags:
      - Usuário
    post:
      consumes:
      - application/json
      parameters:
      - description: CPF
        in: body
        name: cpf
        required: true
        schema:
          type: string
      - description: Nome
        in: body
        name: nome
        required: true
        schema:
          type: string
      - description: Nome de Usuário
        in: body
        name: nome_de_usuario
        required: true
        schema:
          type: string
      - description: Email
        in: body
        name: email
        required: true
        schema:
          type: string
      - description: Senha
        in: body
        name: senha
        required: true
        schema:
          type: string
      - description: Data de Nascimento
        in: body
        name: data_de_nascimento
        required: true
        schema:
          type: string
      - description: Plano de Assinatura
        in: body
        name: plano_de_assinatura
        required: true
        schema:
          type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/Erro'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/Erro'
      summary: Cria um usuário
      tags:
      - Usuário
  /api/usuario/:nome_de_usuario:
    delete:
      consumes:
      - application/json
      parameters:
      - description: Nome de Usuário
        in: path
        name: nome_de_usuario
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/Erro'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/Erro'
      summary: Remove um usuário
      tags:
      - Usuário
    get:
      consumes:
      - application/json
      parameters:
      - description: Nome de Usuário
        in: path
        name: nome_de_usuario
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Usuario'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/Erro'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/Erro'
      summary: Retorna o usuário com o nome de usuário fornecido
      tags:
      - Usuário
    patch:
      consumes:
      - application/json
      parameters:
      - description: Nome de Usuário
        in: path
        name: nome_de_usuario
        required: true
        type: string
      - description: CPF
        in: body
        name: cpf
        schema:
          type: string
      - description: Nome
        in: body
        name: nome
        schema:
          type: string
      - description: Nome de Usuário
        in: body
        name: nome_de_usuario
        schema:
          type: string
      - description: Email
        in: body
        name: email
        schema:
          type: string
      - description: Senha
        in: body
        name: senha
        schema:
          type: string
      - description: Data de Nascimento
        in: body
        name: data_de_nascimento
        schema:
          type: string
      - description: Plano de Assinatura
        in: body
        name: plano_de_assinatura
        schema:
          type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/Erro'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/Erro'
      summary: Atualiza um usuário
      tags:
      - Usuário
  /api/usuario/login:
    post:
      consumes:
      - application/json
      parameters:
      - description: Nome de Usuário
        in: body
        name: nome_de_usuario
        schema:
          type: string
      - description: Email
        in: body
        name: email
        schema:
          type: string
      - description: Senha
        in: body
        name: senha
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/Erro'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/Erro'
      summary: Autentica o usuário
      tags:
      - Usuário
swagger: "2.0"
