version: "3.8"

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
      target: env
    volumes:
      - ./:/app
    ports:
      - "8080:8080"
    command: sh -c "go get ./... && make watch"
