name: Go-test
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 'lts'
      - name: Install dependencies Node
        run: npm install
      - name: Build Node
        run: npm run build

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.6'
      - name: Install templ
        run: go install github.com/a-h/templ/cmd/templ@latest
      - name: Build Go
        run: templ generate && go build -v ./...
      - name: Test with the Go CLI
        run: go test ./... 
