name: Build and Test
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.6'
      - name: Build Go
        run: go build -v ./...
      - name: Copy .env.example
        run: cp .env.example .env
      - name: Test with the Go CLI
        run: make test
