name: Fly Deploy in Staging
on:
  push:
    branches:
      - stage

jobs:
  deploy:
    name: Deploy App
    runs-on: ubuntu-latest
    concurrency: deploy-group
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy -c fly.toml.staging --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_STAGING_API_TOKEN }}
